### ISSUE TITLE
Switch to postgresql from sqlite3

### ISSUE THREAD

**Issue by inlibra-cpa** [jimenezmiguela/Help_Find#20]
Install PostgreSql: https://www.postgresql.org/download/

1. gemfile:
add gem "pg"
remove gem "sqlite"

2. Configure database.yml:
Manually modify our database.yml to add PostgreSQL related configuration

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sample_development            #insert the name of your app instead of "sample"

test:
  <<: *default
  database: sample_test          #insert the name of your app instead of "sample"

production:
  <<: *default
  database: sample_production      #insert the name of your app instead of "sample"
  username: sample                 #insert the name of your app instead of "sample"
  password: <%= ENV['SAMPLE_DATABASE_PASSWORD'] %>                 #insert the name of your app instead of "sample"

3. console:
Install Postgresql and create a user:
       sudo apt install postgresql libpq-dev
       sudo su postgres
       createuser --interactive
       "your_name"
     y 
     exit
Check version of postgresql
     pg_config --version
To create another user with a password:
     sudo su postgres
     createuser --interactive --pwprompt
     username
     password
     y
     exit
Set default password for a postgresql user: in this case we set password myPassword for user postgres
     sudo -u postgres psql
     ALTER USER postgres PASSWORD 'myPassword';
     \q
Now you can install the gem and run migrations:
     bundle
     rails db:create db:migrate             #if you are creating new app
     rake db:setup db:migrate                       #if you are switching from sqlite or other db to postgresql
     rails s         #run your server to see if it works

That’s it!

To use the Rails 6 db system change command, you simply need to specify the new database adapter with the --to option.     #me personally got the error: invalid option: --to=postgresql

rails db:system:change --to=postgresql
rails db:system:change --to=mysql
rails db:system:change --to=sqlite3
rails db:system:change --to=oracle
rails db:system:change --to=frontbase
rails db:system:change --to=sqlserver
rails db:system:change --to=jdbc

Keep in mind, you may need to change the version numbers of the database adapter in your Gemfile after running this command.

**Comment by jimenezmiguela** [comment]
Are instructions above something you did, or requesting something we have to do?

**Comment by inlibra-cpa** [comment]
These steps are I went through to install the PostgreSql; just description
of what I did.
