### ISSUE TITLE
Deploy to heroku

### ISSUE THREAD

**Issue by inlibra-cpa** [jimenezmiguela/Help_Find#31]
UPDATE:

Miguel deployed the apps himself, so, the status of this issue is undetermined right now, as I was an assignee from the very first mention of HEROKU. The purpose of switching to PostgreSQL issue/ticket (which is now done and closed) was to deploy the project at the end of the practicum to Heroku. We are working on debugging after deployment and creating an automatic connection to github. 

***

As we are going to switch from SQLite3 to PostgreSQL(pending approval), we will be able to deploy our project to Heroku later.
I'm searching for additional info on the issue and trying to dive deep into how to deploy an app like ours(API/Back-end/Front-end)
Here are general instructions to deploy it locally:
1. GO to heroku.com and create an account.

     sudo snap install heroku
     sudo snap install heroku --classic
     heroku create
     Press any key to open up the browser to login or q to exit
     go to the link provided to log in
     heroku login -i      #if you'll get an IP mismatch error; type your credentials manually
     git push heroku master

**Comment by olegkolyaka78** [comment]
Don't see any further issues with using Heroku. Lets try. Please share some instructions with us here.
